version: 2.1
orbs:
  coveralls: coveralls/coveralls@1.0.4
jobs:
  build:
    working_directory: ~/my-project
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: my-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: my-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Unit Test
          command: npm run test -- --watch=false --code-coverage
      - run:
          name: End to End Test
          command: npm run e2e
      - store_artifacts:
          path: ./coverage
      - coveralls/upload
